// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TelegramBots.BotAlarm.Migrations
{
    public partial class AddBroadcastSettings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "Settings_BroadcastMessageDuringBroadcast",
                schema: "alarm",
                table: "Chats",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Settings_BroadcastMessageDuringBroadcast",
                schema: "alarm",
                table: "Chats");
        }
    }
}
